name: 'hermes-messenger'
base: 'core20'
version: '0.0.4+git'
summary: 'Hermes Messenger is an unofficial Facebook Messenger app.' 
description: |
   Hermes Messenger is a unofficial electron Facebook messenger app made for linux smartphone (eg: librem 5, pinephone)
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
license: GPL-3.0

architectures:
  - build-on: arm64
  - build-on: amd64

apps:
  hermes-messenger:
    extensions: [gnome-3-38]
    plugs:
      gnome-3-38-2004:
        default-provider: gnome-3-38-2004
        interface: content
        target: $SNAP/gnome-platform
      gtk-3-themes:
        default-provider: gtk-common-themes
        interface: content
        target: $SNAP/data-dir/themes
      icon-themes:
        default-provider: gtk-common-themes
        interface: content
        target: $SNAP/data-dir/icons
      sound-themes:
        default-provider: gtk-common-themes
        interface: content
        target: $SNAP/data-dir/sounds
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu

    command: Hermes-Messenger/Hermes-Messenger
parts:
  hermes-messenger:
    source: https://github.com/mrbn100ful/hermes-messenger.git
    source-subdir: .
    source-type: git
    plugin: nil
    override-build: |
        if [ -n "$http_proxy" ]; then
         export ELECTRON_GET_USE_PROXY=1
         export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
         export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
        fi
        npm config set user 0
        npm config set unsafe-perm true
        npm install electron electron-packager electron-builder
        npx electron-packager ./ --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./Hermes-Messenger-* $SNAPCRAFT_PART_INSTALL/Hermes-Messenger
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
    