name: hermes-messenger
version: 0.0.3
summary: Hermes Messenger is an unofficial Facebook Messenger app.
description: |
  Hermes Messenger is a unofficial electron Facebook messenger app made for linux smartphone (eg: librem 5, pinephone)
  Inspired by Caprine

grade: stable
confinement: classic

parts:
  electron-app:
    plugin: nodejs
    source: https://github.com/MrBn100ful/Hermes-Messenger.git
    node-engine: 14.16.0
    stage-packages:
      - libappindicator1
    build: npm run dist

apps:
  hermes-messenger:
    command: bin/desktop-launch $SNAP/app/hermes-messenger
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - browser-support
      - network
      - gsettings
      - pulseaudio