name: hermes-messenger # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.0.3+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hermes Messenger is an unofficial Facebook Messenger app. # 79 char long summary
description: |
   Hermes Messenger is a unofficial electron Facebook messenger app made for linux smartphone (eg: librem 5, pinephone)
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
license: GPL-3.0

apps:
  hermes-messenger:
    extensions: [gnome-3-34]
    plugs:
    - desktop
    - desktop-legacy
    - home
    - x11
    - wayland
    - unity7
    - browser-support
    - network
    - gsettings
    - audio-playback
    - pulseaudio
    - opengl
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    command: Hermes-Messenger/Hermes-Messenger
parts:
  hermes-messenger:
    source: https://github.com/mrbn100ful/hermes-messenger.git
    source-subdir: .
    source-type: git
    plugin: nil
    override-build: |
        echo $SNAPCRAFT_PART_INSTALL
        ls -al
        if [ -n "$http_proxy" ]; then
         export ELECTRON_GET_USE_PROXY=1
         export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
         export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
        fi
        npm config set user 0
        npm config set unsafe-perm true
        npm install electron electron-packager electron-builder
        ls -al
        npx electron-packager ./ --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./Hermes-Messenger-* $SNAPCRAFT_PART_INSTALL/Hermes-Messenger
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
      - libnss3
      - libnspr4