name: hermes-messenger # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.0.3+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hermes Messenger is an unofficial Facebook Messenger app. # 79 char long summary
description: |
   Hermes Messenger is a unofficial electron Facebook messenger app made for linux smartphone (eg: librem 5, pinephone)
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
license: GPL3

apps:
  hermes-messenger:
    command: hermes-messenger

parts:
  hermes-messenger:
    source: .
    plugin: npm
    npm-node-version: 14.16.0